### ISSUE TITLE
Can't get "--input-file" to work

### ISSUE THREAD

**Issue by nohaj** [rikatz/kubepug#135]
Hello,

I tried to use the --input-file option with a single file, a folder or things like "cat *.yaml" but it never works.

I always get : 

`level=warning msg="Found invalid yaml: ./FILENAME: yaml: did not find expected node content. Skipping to next"`

For exemple with the gitlab-runner helm charts : 

```
helm pull gitlab/gitlab-runner --version 0.23.0
tar xzvf gitlab-runner-0.23.0.tgz 
kubepug --k8s-version=v1.15.5 --input-file=./gitlab-runner/templates
time="2020-12-07T12:07:09+01:00" level=warning msg="Found invalid yaml: ./gitlab-runner/templates//NOTES.txt: yaml: did not find expected node content. Skipping to next"
time="2020-12-07T12:07:09+01:00" level=warning msg="Found invalid yaml: ./gitlab-runner/templates//_cache.tpl: yaml: did not find expected node content. Skipping to next"
time="2020-12-07T12:07:09+01:00" level=warning msg="Found invalid yaml: ./gitlab-runner/templates//_env_vars.tpl: yaml: did not find expected node content. Skipping to next"
time="2020-12-07T12:07:09+01:00" level=warning msg="Found invalid yaml: ./gitlab-runner/templates//_helpers.tpl: yaml: did not find expected alphabetic or numeric character. Skipping to next"
time="2020-12-07T12:07:09+01:00" level=warning msg="Found invalid yaml: ./gitlab-runner/templates//configmap.yaml: yaml: line 70: could not find expected ':'. Skipping to next"
time="2020-12-07T12:07:09+01:00" level=warning msg="Found invalid yaml: ./gitlab-runner/templates//deployment.yaml: yaml: line 22: could not find expected ':'. Skipping to next"
time="2020-12-07T12:07:09+01:00" level=warning msg="Found invalid yaml: ./gitlab-runner/templates//hpa.yaml: yaml: did not find expected node content. Skipping to next"
time="2020-12-07T12:07:09+01:00" level=warning msg="Found invalid yaml: ./gitlab-runner/templates//role-binding.yaml: yaml: did not find expected node content. Skipping to next"
time="2020-12-07T12:07:09+01:00" level=warning msg="Found invalid yaml: ./gitlab-runner/templates//role.yaml: yaml: did not find expected node content. Skipping to next"
time="2020-12-07T12:07:09+01:00" level=warning msg="Found invalid yaml: ./gitlab-runner/templates//secrets.yaml: yaml: did not find expected node content. Skipping to next"
time="2020-12-07T12:07:09+01:00" level=warning msg="Found invalid yaml: ./gitlab-runner/templates//service-account.yaml: yaml: did not find expected node content. Skipping to next"
RESULTS:
Deprecated APIs:


Deleted APIs:

```

What am I doing wrong ?

I'm trying this option because i don't manage to have the kubepug command working with serviceaccount that can only access one specific namespace (but if it can be done I will take this way).

`time="2020-12-07T10:27:52Z" level=fatal msg="Failed to list objects in the cluster. Permission denied! Please check if you have the proper authorization"`

Regards,

Johan

**Comment by rikatz** [comment]
Hello,

Can you please post one of the yaml files in some pastebin or gist? 

About the usage inside the cluster, I've never tried this approach but need to, and maybe also map some RBACs to deploy it as a job inside kubernetes :)

Thanks!

**Comment by nohaj** [comment]
Hello,

You can find the files there : https://gitlab.com/gitlab-org/charts/gitlab-runner/-/tree/master/templates

It would be nice to have theses new features ! :)

Thank you

**Comment by danielhoherd** [comment]
@rikatz given that several people (myself included) are reporting problems with yaml files, would it make sense to have some tests that run in CI against problematic yaml files one at a time? People could make PRs with their problematic files and others could either point out their problem or they would become valid test cases against kubepug.

**Comment by rikatz** [comment]
Yes sure! Would love to see this! Sorry folks I've been pretty busy but want to start smashing those bugs again :)

**Comment by rikatz** [comment]
Hey folks, took the day to debug this. Apparently there is something wrong with the manifest that is making yaml parser get lost. 

I'm trying to figure out in which part it is problematic, and will fix here.

Thanks for reporting this!

**Comment by rikatz** [comment]
So  we have two different problems :)

* YAML parsing is hard... (to not say other word!) but now it's working. I did reduced the logging threshold when parsing the YAML file kind and apiVersion to info, as it's not quite true.

Still, I fixed some things on the yaml parsing, moving the spliting from the library directly to bytes (everytime --- is found we know there is a new file). It's working fine

Finally, I have moved to Kubernetes yaml library, which seems better and more stable than the official one 🤷 

* Standard input reading. Using /dev/stdin seems not to be the right/working way of doing it. 
I'm fixing this, so instead of passing "/dev/stdin" the idea is passing "-" as input file and leaving golang compiler to read from os.STDIN :)

**Comment by rikatz** [comment]
Will make a new release today! Let me know if this problem is solved folks.

This gave me some idea of having kubepug also testing helm charts directly (like, you point to some chart, it downloads, renders and attempts to verify) but no promises, as I'm getting a ton of other stuff to do :(

If someone wants to play/try implementing this, LMK and I can help :)
