### ISSUE TITLE
Failed communicating with k8s

### ISSUE THREAD

**Issue by goseind** [rikatz/kubepug#233]
When I run `kubectl deprecations` on my clusters, I receive the following error:

`I0209 12:53:17.863265   10353 request.go:665] Waited for 1.189010251s due to client-side throttling, not priority and fairness, request: GET:https://xxxxxxx/apis/bitnami.com/v1alpha1?timeout=32s
time="2022-02-09T12:53:20+01:00" level=fatal msg="Failed communicating with k8s while discovering the object preferred name and gv. Error: unable to retrieve the complete list of server APIs: external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request"`

The clusters run gke version 1.20.12-gke.1500.

**Comment by david1155** [comment]
Please advise how to add an option to skip apiservices in the False state.
For example in resources.go:
```
	for _, rl := range resourcelist {
		for i := range rl.APIResources {
		if rl.GroupVersion == "external.metrics.k8s.io/v1beta1" {
			continue
		}
```

**Comment by rikatz** [comment]
hey folks, so the real issue here is that the discovery side (that happens on Kubernetes API side) will always try to go to each APIService configured, and ask for the existing resources. 

We need to run the API discovery to populate "what APIs we are concerned with", but the function does a single call (in fact, the rl.APIResources will receive a full list of APIs on Kubernetes side).

I can check if there is a discovery we can run that is "failable" from the Server side, and use this method instead of the regular one.

Can you also check the latest alpha release (v1.5.0) to see if this release improves on other bugs?

Thanks!

**Comment by rikatz** [comment]
The next alpha release will fix it :)
