### ISSUE TITLE
No output when using 1.6.0

### ISSUE THREAD

**Issue by marevers** [rikatz/kubepug#427]
When using kubepug 1.6.0, the main command has no output.

Example:
```bash
kubepug --k8s-version v.1.27.3
```

Result is that the prompt returns without outputting anything.

Running the same command with 1.5.1 returns the expected output:
```bash
RESULTS:
Deprecated APIs:

ComponentStatus found in /v1
         ├─ ComponentStatus (and ComponentStatusList) holds the cluster validation info. Deprecated: This API is deprecated in v1.19+
                -> GLOBAL: scheduler
                -> GLOBAL: controller-manager
                -> GLOBAL: etcd-0
                -> GLOBAL: etcd-1


Deleted APIs:
```

I've also tried downloading this new data.json file and calling the command with `--database data.json` but this has no effect.

**Comment by rikatz** [comment]
Hey Martin,

Yes, this is right :) We just return errors now when there is really some deprecated item on your cluster. The `ComponentStatus` is a really specific case, because besides it being deprecated, it is not a real object that you can replace, but just something that "is deprecated but nothing to do"

The previous version we used to read swagger.json for this Deprecated fields and not really what there's on the API, in this new version the file is generated based on the Kubernetes API.

If you want to take a look on what data.json looks for, look at https://kubepug.xyz/deprecations/ :) 

This is a table containing all the Deprecated and Deleted APIs reported by Kubernetes that we target!

Thanks for using the project!

**Comment by rikatz** [comment]
you are right :) It missed some message on it and the UX is bad :)

I will implement it maybe today during afternoon, just to print that no deprecated or deleted APIs were found as you suggested :)

Thanks!!

**Comment by marevers** [comment]
Perfect! Thank you.

**Comment by rikatz** [comment]
Done, I will make a v1.6.1 release. Take a look into the PR, it is pretty simple just printing a message on the end.
