### ISSUE TITLE
kubepug is not finding deprecated APIs

### ISSUE THREAD

**Issue by estahn** [rikatz/kubepug#92]
@rikatz With implementing #82 we're not able to see deprecations anymore. Thinking about the implementation I was wondering how is `kubepug` able to identify deprecations as in my mind the Kube API will return whatever object you're requesting but not the original source, is that assumption correct?

I was wondering if you could read from `metadata.annotations."kubectl.kubernetes.io/last-applied-configuration"` instead and use this as the source for analysis.

Thoughts?

**Comment by rikatz** [comment]
Yep, I'm taking a look at it.

A simple test I'm making is create a Ingress object in k8s 1.14 (which have this as preferred in extensions/v1beta1) and then running pug with swagger from master and the object is not being found.

Will see what's going on

**Comment by estahn** [comment]
@rikatz I wrote a little helper script to work around the issue. I don't think it's possible to directly retrieve the resource that was applied. As far as I understand Kubernetes keeps an internal state and the Kubernetes API will return that internal state based on what you're requesting, e.g. `extensions/v1beta1` or `apps/v1`. The only way I have found to retrieve what was applied is through the annotation `kubectl.kubernetes.io/last-applied-configuration`.

I'm still using kubepug with the `--input-file` feature :)

```bash
#!/usr/bin/env bash

namespaces=$(kubectl get namespaces -o=jsonpath="{.items[*].metadata.name}")
apiresources=$(kubectl api-resources -oname --namespaced=true | grep -v bindings | grep -v pod)
kubeversion=v1.16.10
hashmapdir=/tmp/deprecation

rm -rf $hashmapdir

echo "namespace,apiresource,resource,instance" > results.csv
for namespace in $namespaces; do
    for apiresource in $apiresources; do
        resources=$(kubectl get $apiresource -n $namespace -o=jsonpath="{.items[*].metadata.name}")

        for resource in $resources; do
            echo "$namespace $apiresource $resource $instance"
            lastapplied=$(kubectl apply view-last-applied -ojson -n $namespace $apiresource $resource)

            deprecation=$(echo $lastapplied | kubectl deprecations --k8s-version $kubeversion --error-on-deleted --error-on-deprecated --format plain --input-file /dev/stdin 2>&1)
            deprecated=$?

            instance=$(echo $lastapplied | jq -r '.metadata.labels."app.kubernetes.io/instance"')

            if [ "$deprecated" -ne 0 ]; then
                echo "$namespace,$apiresource,$resource,$instance" >> results.csv

                mkdir -p $hashmapdir/$instance
                echo $deprecation > $hashmapdir/$instance/$apiresource.$resource
            fi
        done
    done
done
```

**Comment by rikatz** [comment]
@estahn Tks for helping in this :) 

Yeap, the problem is that annotations, IMO are not a trusted source of information, as they might be changed and masquerade some real information. As far as I remember, those are also added with kubectl apply but maybe not created with kubectl create so this might be a problem.

I'm sorry about taking so long to take a look at this, but thinks at job are in a rush and I'm having not enough time to take care of this, but I'll try to correct this weekend the behavior.

Thank you again for the help :)

**Comment by rikatz** [comment]
I'll write here so I wont forget :)

I'm using now a method called ``ServerPreferredResources`` from client-go that finds each preferred API GroupVersion for each object, but it seems that while some are returned well, others aren't. As an example:

```
extensions/v1beta1
        Deployment --- deployments
extensions/v1beta1
        Ingress --- ingresses
apps/v1
        Deployment --- deployments
networking.k8s.io/v1beta1
        Ingress --- ingresses
```

This is weird and in the same time, it makes sense as the API needs to keep the compability. Maybe one way is to index the whole group/version/kind instead of just the kind, but this might lead to some undesired behavior. I'm not pretty sure when upgrading from v1.14 to v1.16, as an example the objects get converted or not and also if the program needs, in this case to check only for future deleted api groups. I'll make some further reflections on this.
